/*
 * Copyright (c) 2025 Artem Demchyshyn
 *
 * Licensed under the MIT License. See LICENSE file in the project root.
 */
package io.github.demchaav.gemini.request_response.response;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.github.demchaav.gemini.request_response.content.Content;
import io.github.demchaav.gemini.request_response.content.part.Part;
import io.github.demchaav.gemini.request_response.response.candidate.Candidate;
import io.github.demchaav.gemini.request_response.response.usageMeta.UsageMetadata;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import lombok.Builder;
import lombok.extern.slf4j.Slf4j;

/**
 * Root response model for Gemini API calls.
 *
 * @since 1.0.4
 */
@Slf4j
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
public record GeminiResponse(
    List<Prediction> predictions,
    /** List of response candidates generated by the model. */
    List<Candidate> candidates,

    /** Metadata about token usage for this request and response. */
    UsageMetadata usageMetadata,

    /** The model and version used for generation. For example: gemini-1.5-flash-002. */
    String modelVersion) {
  /**
   * Returns a role-aware textual representation of all candidate content.
   *
   * @return candidate content formatted with roles, or {@code null} when no candidates exist
   * @since 1.0.4
   */
  public String contentAsString() {
    if (candidates == null) {
      log.error(" {} was null in stream processing!!", "candidates");
      return null;
    }
    List<Content> contentList =
        new ArrayList<>(candidates.stream().map(Candidate::content).toList());

    return contentList.stream()
        .map(
            content ->
                String.format(
                    "role: %s%nmessage: \"%s\"%n",
                    content.role(),
                    content.parts().stream().map(Part::text).collect(Collectors.joining()).trim()))
        .collect(Collectors.joining());
  }

  /**
   * Flattens all candidate text parts into a single string.
   *
   * @return flattened text content, or {@code null} when no candidates exist
   * @since 1.0.4
   */
  public String asString() {
    if (candidates == null) {
      log.error(" {} was null!!", "candidates");
      return null;
    }
    List<Content> contentList =
        new ArrayList<>(candidates.stream().map(Candidate::content).toList());

    return contentList.stream()
        .map(content -> content.parts().stream().map(Part::text).collect(Collectors.joining()))
        .collect(Collectors.joining());
  }

  /**
   * Prints the response content to {@link System#out} with a lightweight typing effect.
   *
   * @since 1.0.4
   */
  public void printContent() {
    printContent(System.out);
  }

  /**
   * Prints the response content to the supplied stream with a lightweight typing effect.
   *
   * @param output stream that should receive the rendered content
   * @since 1.0.4
   */
  public void printContent(PrintStream output) {
    PrintStream stream = Objects.requireNonNull(output, "output must not be null");
    for (char character :
        Objects.requireNonNull(asString(), "response content must not be null").toCharArray()) {
      stream.print(character);
      stream.flush();
      try {
        Thread.sleep(6);
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        log.error("Interrupted while rendering response content", e);
        throw new IllegalStateException("Interrupted while rendering response content.", e);
      }
    }
  }

  /**
   * Groups candidate content by role.
   *
   * @return a map keyed by role
   * @since 1.0.4
   */
  public Map<String, List<Content>> takeContentAsMap() {
    return candidates.stream()
        .collect(
            Collectors.groupingBy(
                content -> content.content().role(),
                Collectors.mapping(candidate -> candidate.content(), Collectors.toList())));
  }
}
