package org.gemini.core.client.request_response.response;

import lombok.Builder;
import org.gemini.core.client.request_response.response.candidate.Candidate;
import org.gemini.core.client.request_response.response.usageMeta.UsageMetadata;

import java.util.List;

/**
 * Root response model for Gemini API calls
 */
@Builder
public record GeminiResponse(
        /**
         * List of response candidates generated by the model.
         */
        List<Candidate> candidates,

        /**
         * Metadata about token usage for this request and response.
         */
        UsageMetadata usageMetadata,

        /**
         * The model and version used for generation.
         * For example: gemini-1.5-flash-002.
         */
        String modelVersion
) {
}
